# Generated by Django 5.2.15 on 2026-06-30 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='backlog', max_length=20)),
                ('priority_score', models.FloatField(default=0, help_text='Composite priority score — populated by AI Prioritization Assistant (Phase 17)')),
                ('target_quarter', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=10)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('linked_features', models.ManyToManyField(blank=True, help_text='Raw feature requests this roadmap item addresses', related_name='roadmap_items', to='features.feature')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_roadmap_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score'],
            },
        ),
    ]
