# Generated by Django 5.2.15 on 2026-06-30 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight_type', models.CharField(choices=[('feedback_theme', 'Feedback Theme Analysis'), ('churn_risk', 'Churn Risk Explanation'), ('prioritization', 'Feature Prioritization Recommendation'), ('copilot_answer', 'AI Copilot Q&A Response'), ('roadmap_suggestion', 'Roadmap Suggestion')], max_length=30)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('regenerated', 'Regenerated')], default='generated', max_length=20)),
                ('prompt_input', models.TextField(help_text='What was sent to the AI — for debugging and prompt iteration')),
                ('response_text', models.TextField(help_text="The AI's generated insight")),
                ('model_used', models.CharField(help_text="e.g. 'meta-llama/llama-3-8b' via OpenRouter", max_length=100)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('customer_account', models.ForeignKey(blank=True, help_text='Null for org-wide insights not tied to a specific account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='accounts.customeraccount')),
                ('generated_for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.TextField()),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
                ('response_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_query', to='ai_engine.aiinsight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
