# Generated by Django 5.2.15 on 2026-06-30 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(help_text="e.g. 'feature_request_created', 'dashboard_viewed' — matches event taxonomy", max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Event-specific properties as defined in the event taxonomy')),
                ('source', models.CharField(choices=[('mixpanel', 'Mixpanel'), ('manual', 'Manual'), ('internal', 'Internal Tracking')], default='internal', max_length=20)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='accounts.customeraccount')),
                ('user', models.ForeignKey(blank=True, help_text='Which user at the customer account triggered this event, if known', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='analytics_u_event_n_a5a35a_idx'), models.Index(fields=['customer_account', 'event_name'], name='analytics_u_custome_cd000a_idx')],
            },
        ),
    ]
