# Generated by Django 5.2.15 on 2026-06-30 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='The raw feedback text')),
                ('source', models.CharField(choices=[('survey', 'In-App Survey'), ('support_ticket', 'Support Ticket'), ('sales_call', 'Sales Call Notes'), ('email', 'Email'), ('manual', 'Manually Entered'), ('nps', 'NPS Response')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('linked', 'Linked to Feature'), ('archived', 'Archived')], default='new', max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, help_text='-1.0 (very negative) to 1.0 (very positive). Set by AI engine.', null=True)),
                ('urgency_score', models.FloatField(blank=True, help_text='0.0 to 1.0. Set by AI engine.', null=True)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='accounts.customeraccount')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Internal user who logged this feedback, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme_name', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in this theme assignment, 0.0 to 1.0')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='feedback.feedback')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
