# Generated by Django 5.2.15 on 2026-06-30 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('jira', 'Jira'), ('mixpanel', 'Mixpanel')], max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific settings, e.g. Jira project key')),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'provider')},
            },
        ),
    ]
