# Generated by Django 5.2.15 on 2026-06-30 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('under_review', 'Under Review'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('declined', 'Declined')], default='proposed', max_length=20)),
                ('vote_count', models.IntegerField(default=0)),
                ('organization_account', models.ForeignKey(help_text='The customer account that originated this request', on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to='accounts.customeraccount')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
