# Generated by Django 5.2.15 on 2026-06-30 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composite_score', models.FloatField(help_text='0-100 overall health score')),
                ('usage_score', models.FloatField(default=0, help_text='0-100, based on product usage frequency')),
                ('ticket_score', models.FloatField(default=0, help_text='0-100, inverse of ticket volume/severity')),
                ('sentiment_score', models.FloatField(default=0, help_text='0-100, derived from feedback sentiment')),
                ('adoption_score', models.FloatField(default=0, help_text='0-100, % of available features used')),
                ('payment_score', models.FloatField(default=0, help_text='0-100, based on payment/billing status')),
                ('risk_tier', models.CharField(choices=[('healthy', 'Healthy'), ('moderate', 'Moderate Risk'), ('at_risk', 'At Risk'), ('critical', 'Critical')], default='healthy', max_length=20)),
                ('calculation_method', models.CharField(default='rule_based', help_text="'rule_based' for now; will support 'ml_model' once churn prediction (Phase 14) is live", max_length=50)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='accounts.customeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('intervention_logged', 'Intervention Logged'), ('resolved', 'Resolved'), ('churned', 'Churned')], default='open', max_length=30)),
                ('trigger_reason', models.CharField(help_text="e.g. 'composite_score below 40' or 'ticket_score dropped sharply'", max_length=255)),
                ('intervention_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risk_flags', to=settings.AUTH_USER_MODEL)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='accounts.customeraccount')),
                ('triggering_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_flags', to='health.healthscoresnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
